[package]
name = "life"
version = "0.1.0"
authors = ["Volodymyr Yavdoshenko <v.yavdoshenko@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.5", features = ["cargo"] }
rand = "0.8"
crossterm = "0.22"
